version: "3"
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    container_name: mysql
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: TEST
    restart: always

  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - ./db/mongodb/data/db:/data/db
      - ./db/mongodb/data/logs:/data/logs
      - ./db/mongodb/data/conf:/etc/mongo
    environment:
      - TZ=Asia/Shanghai
      # cache
      - wiredTigerCacheSizeGB=1
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=openIM
#      - MONGO_INITDB_ROOT_PASSWORD=openIM


      #TZ: Asia/Shanghai
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ./db/redis/data:/data
      #redis config file
      #- ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass openIM --appendonly yes