version: "3"
 

services:
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - ./db/mongodb/data/db:/data/db
      - ./db/mongodb/data/logs:/data/logs
      - ./db/mongodb/data/conf:/etc/mongo
    environment:
      - TZ=Asia/Shanghai
      # cache
      - wiredTigerCacheSizeGB=1
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=openIM
#      - MONGO_INITDB_ROOT_PASSWORD=openIM
      #TZ: Asia/Shanghai
    restart: always