version: "3"
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git
services:
  h5:
    image: web:latest
    ports:
      - 80:80
    container_name: h5
    restart: always