version: "3"
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    container_name: mysql
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: TEST
    restart: always